name: Update Computer Status

on:
  repository_dispatch:
    types:
      - register-computer
      - update-status

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Add new computer on register event
        if: ${{ github.event.action == 'register-computer' }}
        run: |
          ID="${{ github.event.client_payload.computer_id }}"
          # skip if already present
          grep -q "\"computer_id\": \"$ID\"" commands.json && exit 0
          # append a blank entry
          jq --arg id "$ID" \
            '.computers += [{ computer_id: $id, status:"" }]' \
            commands.json > tmp.json && mv tmp.json commands.json

      - name: Update status in commands.json
        if: ${{ github.event.action == 'update-status' }}
        run: |
          COMPUTER_ID="${{ github.event.client_payload.computer_id }}"
          STATUS="${{ github.event.client_payload.status }}"
          jq --arg id "$COMPUTER_ID" --arg status "$STATUS" \
            '(.computers[] | select(.computer_id == $id).status) = $status' \
            commands.json > tmp.json && mv tmp.json commands.json

      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add commands.json
          git commit -m "Update computer list/status for ${{ github.event.client_payload.computer_id }}" || echo "No changes"
          git push
